# Site settings
title: Reproducing Timing-dependent Flaky Tests in Android Apps via A Single Delay
description: This page contains the dataset used in the ICSE 2023 submission titled "Reproducing Timing-dependent Flaky Tests in Android Apps via A Single Delay".
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: Reproducing Timing-dependent Flaky Tests in Android Apps via A Single Delay
user_description: This page contains the dataset used in the ICSE 2023 submission titled "Reproducing Timing-dependent Flaky Tests in Android Apps via A Single Delay".
user_title: This page contains the dataset used in the ICSE 2023 submission titled "Reproducing Timing-dependent Flaky Tests in Android Apps via A Single Delay".
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

